# Generated by Django 3.2.7 on 2022-06-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('position_name', models.CharField(max_length=50)),
                ('awards', models.IntegerField()),
                ('contents', models.TextField()),
                ('skills', models.CharField(max_length=50)),
                ('write_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
