# Generated by Django 3.2.7 on 2022-06-17 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='write_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
